// Generated by gencpp from file sia_serial/EePose.msg
// DO NOT EDIT!


#ifndef SIA_SERIAL_MESSAGE_EEPOSE_H
#define SIA_SERIAL_MESSAGE_EEPOSE_H

#include <ros/service_traits.h>


#include <sia_serial/EePoseRequest.h>
#include <sia_serial/EePoseResponse.h>


namespace sia_serial
{

struct EePose
{

typedef EePoseRequest Request;
typedef EePoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EePose
} // namespace sia_serial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sia_serial::EePose > {
  static const char* value()
  {
    return "f192399f711a48924df9a394d37edd67";
  }

  static const char* value(const ::sia_serial::EePose&) { return value(); }
};

template<>
struct DataType< ::sia_serial::EePose > {
  static const char* value()
  {
    return "sia_serial/EePose";
  }

  static const char* value(const ::sia_serial::EePose&) { return value(); }
};


// service_traits::MD5Sum< ::sia_serial::EePoseRequest> should match 
// service_traits::MD5Sum< ::sia_serial::EePose > 
template<>
struct MD5Sum< ::sia_serial::EePoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sia_serial::EePose >::value();
  }
  static const char* value(const ::sia_serial::EePoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sia_serial::EePoseRequest> should match 
// service_traits::DataType< ::sia_serial::EePose > 
template<>
struct DataType< ::sia_serial::EePoseRequest>
{
  static const char* value()
  {
    return DataType< ::sia_serial::EePose >::value();
  }
  static const char* value(const ::sia_serial::EePoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sia_serial::EePoseResponse> should match 
// service_traits::MD5Sum< ::sia_serial::EePose > 
template<>
struct MD5Sum< ::sia_serial::EePoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sia_serial::EePose >::value();
  }
  static const char* value(const ::sia_serial::EePoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sia_serial::EePoseResponse> should match 
// service_traits::DataType< ::sia_serial::EePose > 
template<>
struct DataType< ::sia_serial::EePoseResponse>
{
  static const char* value()
  {
    return DataType< ::sia_serial::EePose >::value();
  }
  static const char* value(const ::sia_serial::EePoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIA_SERIAL_MESSAGE_EEPOSE_H
