// Generated by gencpp from file sia_serial/EeRPY.msg
// DO NOT EDIT!


#ifndef SIA_SERIAL_MESSAGE_EERPY_H
#define SIA_SERIAL_MESSAGE_EERPY_H

#include <ros/service_traits.h>


#include <sia_serial/EeRPYRequest.h>
#include <sia_serial/EeRPYResponse.h>


namespace sia_serial
{

struct EeRPY
{

typedef EeRPYRequest Request;
typedef EeRPYResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EeRPY
} // namespace sia_serial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sia_serial::EeRPY > {
  static const char* value()
  {
    return "cfb6f20560ab4d9cc1d682755cf3b5d4";
  }

  static const char* value(const ::sia_serial::EeRPY&) { return value(); }
};

template<>
struct DataType< ::sia_serial::EeRPY > {
  static const char* value()
  {
    return "sia_serial/EeRPY";
  }

  static const char* value(const ::sia_serial::EeRPY&) { return value(); }
};


// service_traits::MD5Sum< ::sia_serial::EeRPYRequest> should match 
// service_traits::MD5Sum< ::sia_serial::EeRPY > 
template<>
struct MD5Sum< ::sia_serial::EeRPYRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sia_serial::EeRPY >::value();
  }
  static const char* value(const ::sia_serial::EeRPYRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sia_serial::EeRPYRequest> should match 
// service_traits::DataType< ::sia_serial::EeRPY > 
template<>
struct DataType< ::sia_serial::EeRPYRequest>
{
  static const char* value()
  {
    return DataType< ::sia_serial::EeRPY >::value();
  }
  static const char* value(const ::sia_serial::EeRPYRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sia_serial::EeRPYResponse> should match 
// service_traits::MD5Sum< ::sia_serial::EeRPY > 
template<>
struct MD5Sum< ::sia_serial::EeRPYResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sia_serial::EeRPY >::value();
  }
  static const char* value(const ::sia_serial::EeRPYResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sia_serial::EeRPYResponse> should match 
// service_traits::DataType< ::sia_serial::EeRPY > 
template<>
struct DataType< ::sia_serial::EeRPYResponse>
{
  static const char* value()
  {
    return DataType< ::sia_serial::EeRPY >::value();
  }
  static const char* value(const ::sia_serial::EeRPYResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIA_SERIAL_MESSAGE_EERPY_H
