// Generated by gencpp from file sia_serial/EeTraj.msg
// DO NOT EDIT!


#ifndef SIA_SERIAL_MESSAGE_EETRAJ_H
#define SIA_SERIAL_MESSAGE_EETRAJ_H

#include <ros/service_traits.h>


#include <sia_serial/EeTrajRequest.h>
#include <sia_serial/EeTrajResponse.h>


namespace sia_serial
{

struct EeTraj
{

typedef EeTrajRequest Request;
typedef EeTrajResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EeTraj
} // namespace sia_serial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sia_serial::EeTraj > {
  static const char* value()
  {
    return "28e4dd667b29bd35b516ba1d379b7529";
  }

  static const char* value(const ::sia_serial::EeTraj&) { return value(); }
};

template<>
struct DataType< ::sia_serial::EeTraj > {
  static const char* value()
  {
    return "sia_serial/EeTraj";
  }

  static const char* value(const ::sia_serial::EeTraj&) { return value(); }
};


// service_traits::MD5Sum< ::sia_serial::EeTrajRequest> should match 
// service_traits::MD5Sum< ::sia_serial::EeTraj > 
template<>
struct MD5Sum< ::sia_serial::EeTrajRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sia_serial::EeTraj >::value();
  }
  static const char* value(const ::sia_serial::EeTrajRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sia_serial::EeTrajRequest> should match 
// service_traits::DataType< ::sia_serial::EeTraj > 
template<>
struct DataType< ::sia_serial::EeTrajRequest>
{
  static const char* value()
  {
    return DataType< ::sia_serial::EeTraj >::value();
  }
  static const char* value(const ::sia_serial::EeTrajRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sia_serial::EeTrajResponse> should match 
// service_traits::MD5Sum< ::sia_serial::EeTraj > 
template<>
struct MD5Sum< ::sia_serial::EeTrajResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sia_serial::EeTraj >::value();
  }
  static const char* value(const ::sia_serial::EeTrajResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sia_serial::EeTrajResponse> should match 
// service_traits::DataType< ::sia_serial::EeTraj > 
template<>
struct DataType< ::sia_serial::EeTrajResponse>
{
  static const char* value()
  {
    return DataType< ::sia_serial::EeTraj >::value();
  }
  static const char* value(const ::sia_serial::EeTrajResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIA_SERIAL_MESSAGE_EETRAJ_H
