// Generated by gencpp from file sia_serial/JointTraj.msg
// DO NOT EDIT!


#ifndef SIA_SERIAL_MESSAGE_JOINTTRAJ_H
#define SIA_SERIAL_MESSAGE_JOINTTRAJ_H

#include <ros/service_traits.h>


#include <sia_serial/JointTrajRequest.h>
#include <sia_serial/JointTrajResponse.h>


namespace sia_serial
{

struct JointTraj
{

typedef JointTrajRequest Request;
typedef JointTrajResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointTraj
} // namespace sia_serial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sia_serial::JointTraj > {
  static const char* value()
  {
    return "3fc8a9e27b55b9b20a2c846f9e053a5c";
  }

  static const char* value(const ::sia_serial::JointTraj&) { return value(); }
};

template<>
struct DataType< ::sia_serial::JointTraj > {
  static const char* value()
  {
    return "sia_serial/JointTraj";
  }

  static const char* value(const ::sia_serial::JointTraj&) { return value(); }
};


// service_traits::MD5Sum< ::sia_serial::JointTrajRequest> should match 
// service_traits::MD5Sum< ::sia_serial::JointTraj > 
template<>
struct MD5Sum< ::sia_serial::JointTrajRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sia_serial::JointTraj >::value();
  }
  static const char* value(const ::sia_serial::JointTrajRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sia_serial::JointTrajRequest> should match 
// service_traits::DataType< ::sia_serial::JointTraj > 
template<>
struct DataType< ::sia_serial::JointTrajRequest>
{
  static const char* value()
  {
    return DataType< ::sia_serial::JointTraj >::value();
  }
  static const char* value(const ::sia_serial::JointTrajRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sia_serial::JointTrajResponse> should match 
// service_traits::MD5Sum< ::sia_serial::JointTraj > 
template<>
struct MD5Sum< ::sia_serial::JointTrajResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sia_serial::JointTraj >::value();
  }
  static const char* value(const ::sia_serial::JointTrajResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sia_serial::JointTrajResponse> should match 
// service_traits::DataType< ::sia_serial::JointTraj > 
template<>
struct DataType< ::sia_serial::JointTrajResponse>
{
  static const char* value()
  {
    return DataType< ::sia_serial::JointTraj >::value();
  }
  static const char* value(const ::sia_serial::JointTrajResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIA_SERIAL_MESSAGE_JOINTTRAJ_H
