// Generated by gencpp from file sia_serial/EeDelta.msg
// DO NOT EDIT!


#ifndef SIA_SERIAL_MESSAGE_EEDELTA_H
#define SIA_SERIAL_MESSAGE_EEDELTA_H

#include <ros/service_traits.h>


#include <sia_serial/EeDeltaRequest.h>
#include <sia_serial/EeDeltaResponse.h>


namespace sia_serial
{

struct EeDelta
{

typedef EeDeltaRequest Request;
typedef EeDeltaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EeDelta
} // namespace sia_serial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sia_serial::EeDelta > {
  static const char* value()
  {
    return "28e4dd667b29bd35b516ba1d379b7529";
  }

  static const char* value(const ::sia_serial::EeDelta&) { return value(); }
};

template<>
struct DataType< ::sia_serial::EeDelta > {
  static const char* value()
  {
    return "sia_serial/EeDelta";
  }

  static const char* value(const ::sia_serial::EeDelta&) { return value(); }
};


// service_traits::MD5Sum< ::sia_serial::EeDeltaRequest> should match 
// service_traits::MD5Sum< ::sia_serial::EeDelta > 
template<>
struct MD5Sum< ::sia_serial::EeDeltaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sia_serial::EeDelta >::value();
  }
  static const char* value(const ::sia_serial::EeDeltaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sia_serial::EeDeltaRequest> should match 
// service_traits::DataType< ::sia_serial::EeDelta > 
template<>
struct DataType< ::sia_serial::EeDeltaRequest>
{
  static const char* value()
  {
    return DataType< ::sia_serial::EeDelta >::value();
  }
  static const char* value(const ::sia_serial::EeDeltaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sia_serial::EeDeltaResponse> should match 
// service_traits::MD5Sum< ::sia_serial::EeDelta > 
template<>
struct MD5Sum< ::sia_serial::EeDeltaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sia_serial::EeDelta >::value();
  }
  static const char* value(const ::sia_serial::EeDeltaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sia_serial::EeDeltaResponse> should match 
// service_traits::DataType< ::sia_serial::EeDelta > 
template<>
struct DataType< ::sia_serial::EeDeltaResponse>
{
  static const char* value()
  {
    return DataType< ::sia_serial::EeDelta >::value();
  }
  static const char* value(const ::sia_serial::EeDeltaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIA_SERIAL_MESSAGE_EEDELTA_H
