// Generated by gencpp from file sia_serial/EeRPYRequest.msg
// DO NOT EDIT!


#ifndef SIA_SERIAL_MESSAGE_EERPYREQUEST_H
#define SIA_SERIAL_MESSAGE_EERPYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sia_serial
{
template <class ContainerAllocator>
struct EeRPYRequest_
{
  typedef EeRPYRequest_<ContainerAllocator> Type;

  EeRPYRequest_()
    {
    }
  EeRPYRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::sia_serial::EeRPYRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sia_serial::EeRPYRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EeRPYRequest_

typedef ::sia_serial::EeRPYRequest_<std::allocator<void> > EeRPYRequest;

typedef boost::shared_ptr< ::sia_serial::EeRPYRequest > EeRPYRequestPtr;
typedef boost::shared_ptr< ::sia_serial::EeRPYRequest const> EeRPYRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sia_serial::EeRPYRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sia_serial::EeRPYRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sia_serial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sia_serial::EeRPYRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sia_serial::EeRPYRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sia_serial::EeRPYRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sia_serial::EeRPYRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sia_serial::EeRPYRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sia_serial::EeRPYRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sia_serial::EeRPYRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::sia_serial::EeRPYRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::sia_serial::EeRPYRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sia_serial/EeRPYRequest";
  }

  static const char* value(const ::sia_serial::EeRPYRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sia_serial::EeRPYRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::sia_serial::EeRPYRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sia_serial::EeRPYRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EeRPYRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sia_serial::EeRPYRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::sia_serial::EeRPYRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SIA_SERIAL_MESSAGE_EERPYREQUEST_H
